<a href="https://colab.research.google.com/github/pedrohentec/data-science-training/blob/main/Pandas_Transforma%C3%A7%C3%A3o_e_Manipula%C3%A7%C3%A3o_de_Dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Preparando Base de Dados

Nele, vamos trabalhar com um projeto focado em precificação inteligente no âmbito de hospedagem de imóveis.

Trataremos e manipularemos dados que interferem no produto final:

- Dados numéricos
- Dados textuais
- Dados de tempo

In [ ]:
import pandas as pd

In [ ]:
dados = pd.read_json("/content/dados_hospedagem.json")
dados.head()

                                         info_moveis
0  {'avaliacao_geral': '10.0', 'experiencia_local...
1  {'avaliacao_geral': '10.0', 'experiencia_local...
2  {'avaliacao_geral': '10.0', 'experiencia_local...
3  {'avaliacao_geral': '10.0', 'experiencia_local...
4  {'avaliacao_geral': '10.0', 'experiencia_local...

Foi observados que os dados estão aninhados em dicionario, então vamos fazer a normalização desse DataFrame

In [ ]:
dados = pd.json_normalize(dados["info_moveis"])
dados

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,[This clean and comfortable one bedroom sits r...,[Lower Queen Anne is near the Seattle Center (...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[Real Bed, Futon, Futon, Pull-out Sofa, Real B...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$0, $0, $0, $0, $0, $350.00, $350.00, $350.00...","[$0, $0, $0, $20.00, $15.00, $28.00, $35.00, $...","[$110.00, $45.00, $55.00, $52.00, $85.00, $50...."
1,10.0,--,10,[Welcome to the heart of the 'Ballard Brewery ...,"[--, Capital Hill is the heart of Seattle, bor...","[2, 3, 2, 3, 3, 3, 2, 1, 2, 2, 2]","[3, 4, 2, 3, 3, 3, 3, 3, 3, 4, 3]","[5, 6, 8, 3, 3, 5, 4, 5, 6, 7, 4]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$500.00, $300.00, $0, $300.00, $300.00, $360....","[$125.00, $100.00, $85.00, $110.00, $110.00, $...","[$350.00, $300.00, $425.00, $300.00, $285.00, ..."
2,10.0,--,11,[New modern house built in 2013. Spectacular ...,[Upper Queen Anne is a charming neighborhood f...,[4],[5],[7],[Real Bed],"[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$1,000.00]",[$300.00],[$975.00]
3,10.0,--,12,[Our NW style home is 3200+ sq ft with 3 level...,[The Views from our top floor! Wallingford ha...,"[3, 3, 3, 3, 3, 3, 3, 3]","[6, 6, 5, 5, 5, 5, 4, 4]","[6, 6, 7, 8, 7, 7, 6, 6]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$500.00, $500.00, $500.00, $500.00, $500.00, ...","[$225.00, $300.00, $250.00, $250.00, $250.00, ...","[$490.00, $550.00, $350.00, $350.00, $350.00, ..."
4,10.0,--,14,"[Perfect for groups. 2 bedrooms, full bathroom...",[Safeway grocery store within walking distance...,"[2, 3]","[2, 6]","[3, 9]","[Real Bed, Real Bed]","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$300.00, $2,000.00]","[$40.00, $150.00]","[$200.00, $545.00]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,nan,--,5,[Our cozy little bungalow is the perfect place...,[The Queen Anne neighborhood is one of the mos...,"[1, 3, 2, 2, 2, 1, 2, 1, 1, 1, 2, 3, 2, 2, 2, ...","[2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, ...","[3, 2, 2, 3, 3, 2, 3, 2, 2, 3, 3, 3, 2, 3, 2, ...","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{""Cable TV"",""Wireless Internet"",Kitchen,""Free...","[$250.00, $200.00, $0, $0, $0, $200.00, $350.0...","[$35.00, $50.00, $100.00, $100.00, $0, $30.00,...","[$150.00, $200.00, $143.00, $150.00, $350.00, ..."
66,nan,--,6,[Bright clean 2 bedroom 1 bath appartment in t...,[Ballard is the most interesting and ecclectic...,"[1, 1, 3, 2, 1, 3, 2, 2, 1, 2, 2, 2, 1, 2, 1, ...","[2, 3, 3, 2, 2, 3, 2, 3, 2, 2, 2, 2, 4, 3, 3, ...","[3, 3, 2, 3, 3, 3, 2, 3, 3, 3, 2, 2, 4, 4, 3, ...","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,""Cable TV"",Internet,""Wireless Internet"",K...","[$200.00, $200.00, $100.00, $0, $0, $750.00, $...","[$0, $0, $100.00, $0, $75.00, $140.00, $112.00...","[$99.00, $185.00, $250.00, $200.00, $275.00, $..."
67,nan,--,7,[Beautiful end-unit townhome with lots of dayl...,"[Cherry blossoms (Sakura) in the spring, every...","[4, 3, 1, 2, 2, 1, 2, 1, 2, 2]","[3, 4, 3, 3, 3, 3, 3, 3, 3, 4]","[3, 5, 1, 5, 3, 2, 3, 4, 4, 4]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$750.00, $350.00, $500.00, $500.00, $0, $200....","[$300.00, $90.00, $250.00, $100.00, $109.00, $...","[$218.00, $350.00, $450.00, $149.00, $99.00, $..."
68,nan,--,8,[Heart of Ballard new townhome with 4 BRs + ba...,"[--, --, The suite is conveniently located off...","[2, 2, 3, 1, 1, 2, 1, 3, 2, 1, 2, 1, 2, 2, 2, ...","[4, 2, 3, 4, 3, 3, 4, 4, 3, 5, 2, 3, 3, 4, 5, ...","[4, 4, 3, 3, 5, 5, 5, 5, 3, 5, 4, 5, 5, 4, 1, ...","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,Internet,""Wireless Internet"",""Air Conditi...","[$500.00, $150.00, $250.00, $800.00, $0, $500....","[$50.00, $85.00, $150.00, $75.00, $100.00, $80...","[$275.00, $199.00, $400.00, $325.00, $300.00, ..."
69,nan,--,9,[This business-themed modern home features: *...,[Your hosts made Madison Valley their home whe...,"[2, 1]","[3, 4]","[6, 6]","[Real Bed, Real Bed]","[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$1,000.00, $500.00]","[$150.00, $0]","[$250.00, $350.00]"

Para dar continuidade vamos entender o que cada coluna traz de informação:

- **avaliacao_geral:** refere-se à média de notas dadas para a avaliação da hospedagem no imóvel.
- **experiencia_local:** descreve as experiências oferecidas durante a hospedagem no imóvel.
- **max_hospedes:** informa a quantidade máxima de hóspedes que o local permite.
- **descricao_local:** descreve o imóvel.
- **descricao_vizinhanca:** descreve a vizinhança ao redor do imóvel.
- **quantidade_banheiros:** informa a quantidade de banheiros disponíveis.
- **quantidade_quartos:** informa a quantidade de quartos disponíveis.
- **quantidade_camas:** informa a quantidade de camas disponíveis.
- **modelo_cama:** informa o modelo de cama oferecido.
comodidades: informa as comodidades oferecidas pelo imóvel.
- **taxa_deposito:** informa a taxa de depósito mínima para segurança de hospedagem.
- **taxa_limpeza:** informa a taxa cobrada para o serviço de limpeza.
- **preco:** refere-se ao preço base a ser cobrado pela diária no imóvel.

# Desagrupar Dados

Ao importar nossos dados, podemos observar que da coluna "descricao_local" até a coluna "preco", temos informação que estão entre colchetes, ou seja, agrupadas em listas.

Vamos estar desagrupando para podermos trabalhar e analisá-los melhor.

Através do método `explode()`.

O `explode()` transforma cada elemento de uma lista em uma linha. Nele passando o parâmetro das colunas que desejamos fazer essa transformação

In [ ]:
colunas = list(dados.columns)
colunas

['avaliacao_geral',
 'experiencia_local',
 'max_hospedes',
 'descricao_local',
 'descricao_vizinhanca',
 'quantidade_banheiros',
 'quantidade_quartos',
 'quantidade_camas',
 'modelo_cama',
 'comodidades',
 'taxa_deposito',
 'taxa_limpeza',
 'preco']

In [ ]:
# Observado que precisamos só trabalhar da coluna descricao_local, vamos utilizar o indice:

dados = dados.explode(colunas[3:])
dados

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
0,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
0,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
0,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
0,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,nan,--,8,Beautiful craftsman home in the historic Wedgw...,--,3,4,5,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$178.00,$299.00
68,nan,--,8,Located in a very easily accessible area of Se...,"Quiet, dead end street near I-5. The proximity...",2,4,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",$0,$99.00,$199.00
68,nan,--,8,This home is fully furnished and available wee...,--,1,3,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",$0,$0,$400.00
69,nan,--,9,This business-themed modern home features: *H...,Your hosts made Madison Valley their home when...,2,3,6,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$150.00,$250.00
69,nan,--,9,This welcoming home is in the quiet residentia...,"Despite the quiet, leafy streets of this resid...",1,4,6,Real Bed,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$500.00,$0,$350.00

In [ ]:
# Com isso, precisamos resetar o index pois o método explode replica/repete os indices de cada elemento
# Inplace para atribuir a alteração na variavel e drop para remover os indices antigos

dados.reset_index(inplace=True, drop=True)
dados.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
1,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
2,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
3,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
4,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00

In [ ]:
# Analise os tipos de dados

dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   object
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   object
 6   quantidade_quartos    3818 non-null   object
 7   quantidade_camas      3818 non-null   object
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   object
dtypes: object(13)
memory usage: 387.9+ KB

# Convertendo Dados Numéricos

Foi observado que os tipos de todos os dados estão em `object`, entretanto, para trabalharmos com probilidade e estatística, precisamos ter valores numéricos, com isso vamos utilizar o método `astype()` para fazermos a conversão do tipo `object` para `int` ou `float`

Para isso precisamos importar a biblioteca Numpy, para podermos converter em tanto `int64` quanto `float64`, que são tipos especificos de valores com precisão de 64 bits.

In [ ]:
import numpy as np

In [ ]:
# Nesse caso estamos fazendo a conversão de uma única coluna

dados["max_hospedes"] = dados["max_hospedes"].astype(np.int64)

In [ ]:
colunas_numericas = ["quantidade_banheiros",	"quantidade_quartos",	"quantidade_camas"]

dados[colunas_numericas] = dados[colunas_numericas].astype(np.int64)

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   object
dtypes: int64(4), object(9)
memory usage: 387.9+ KB

In [ ]:
# Convertendo em valor float

dados["avaliacao_geral"] = dados["avaliacao_geral"].astype(np.float64)

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   object
dtypes: float64(1), int64(4), object(8)
memory usage: 387.9+ KB

Porém agora, temos as últimas 3 colunas:

- taxa_deposito
- taxa_limpeza
- preco

Essas colunas, possuem sifrão e virgulas, e não podemos usar o `astype()`, por isso, precisamos tratar isso antes de fazer a conversão desses valores e passar para `float`

# Números em Strings

Agora vamos trabalhar com a coluna de preço, onde vamos substituir o tipo de dos dados para float, porém fazendo algumas manipulações para que isso seja possível:

In [ ]:
# Utilizando o replace, strip e lambda

dados["preco"] = dados["preco"].apply(lambda x: x.replace("$", "").replace(",", "").strip())

In [ ]:
# Aplicando o astype para tentar a conversão do tipo, de string para float

dados["preco"] = dados["preco"].astype(np.float64)

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   float64
dtypes: float64(2), int64(4), object(7)
memory usage: 387.9+ KB

# Tratando colunas múltiplas

Anteriormente usamos o `apply` que faz a aplicação de uma única colunas.

Agora vamos usar o `applymap`, quando tratamos da conversão de um dataframe, no qual passaremos por cada elemento.

Vamos manipular as colunas:

- taxa_deposito
- taxa_limpeza

In [ ]:
dados[["taxa_deposito", "taxa_limpeza"]] = dados[["taxa_deposito", "taxa_limpeza"]].applymap(lambda x: x.replace("$", "").replace(",", ""))

In [ ]:
dados[["taxa_deposito", "taxa_limpeza"]] = dados[["taxa_deposito", "taxa_limpeza"]].astype(np.float64)

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   float64
 11  taxa_limpeza          3818 non-null   float64
 12  preco                 3818 non-null   float64
dtypes: float64(4), int64(4), object(5)
memory usage: 387.9+ KB

# Análise Textual

Para que possa ser feito uma boa análise textual, podemos realizar a manipulação destes textos de cada colunas para criar um tipo de tokenixação simples.

`Tokenização` é a divisão do texto em `tokens`, sendo unidades menores, podendo ser palavras, sílabas, conjuntos de palavras e etc.

Por se tratar de tokenização simples, iremos fazer a separação por palavras. (tokens sera cada palavra).

Para isso vamos estar iniciando a nossa visualização da coluna `"descricao_local"` e darmos continuidade:

In [ ]:
dados["descricao_local"]

0       This clean and comfortable one bedroom sits ri...
1       Our century old Upper Queen Anne house is loca...
2       Cozy room in two-bedroom apartment along the l...
3       Very lovely and cozy room for one. Convenientl...
4       The “Studio at Mibbett Hollow' is in a Beautif...
                              ...
3813    Beautiful craftsman home in the historic Wedgw...
3814    Located in a very easily accessible area of Se...
3815    This home is fully furnished and available wee...
3816    This business-themed modern home features:  *H...
3817    This welcoming home is in the quiet residentia...
Name: descricao_local, Length: 3818, dtype: object

In [ ]:
# Vamos converter as letras maiúsculas em minúsculas, com isso vamos converter todos esses textos em string e usar o lower()
dados["descricao_local"] = dados["descricao_local"].str.lower()

In [ ]:
dados["descricao_local"]

0       this clean and comfortable one bedroom sits ri...
1       our century old upper queen anne house is loca...
2       cozy room in two-bedroom apartment along the l...
3       very lovely and cozy room for one. convenientl...
4       the “studio at mibbett hollow' is in a beautif...
                              ...
3813    beautiful craftsman home in the historic wedgw...
3814    located in a very easily accessible area of se...
3815    this home is fully furnished and available wee...
3816    this business-themed modern home features:  *h...
3817    this welcoming home is in the quiet residentia...
Name: descricao_local, Length: 3818, dtype: object

Com isso podemos retirar os caracteres que não traz nenhum tipo de informação.

# Remoção de caracteres no texto

Agora vamos estar removendo alguns caracteres que não são úteis e que não nenhum valor para a nossa análise de dados textual.

Para isso, vamos utilizar o replace com regex.
Mas antes precisaremos transformar isso em um tipo de string, ficando dessa forma:

In [ ]:
dados["descricao_local"] = dados["descricao_local"].str.replace("[^a-zA-Z0-9\-\']", " ", regex=True)

Mas que parâmetro voce passou nesse regex ?

- `^` Usado quando queremos negar os próximos valores, tudo que colocar em seguida, ele não vai selecionar para aplicar o replace

- `a-z` todas as letras, do "a" ao "z", minúsculas
- `A-Z` todas as letras, do "A" ao "Z", maiúsculas
- `0-9` todo os números, de 0 a 9
- `\-` hífen
- `\'` apóstrofo

Ou seja, tudo que passamos depois do `^` ele NÃO vai selecionar para aplicar em nosso Regex

Com isso, temos nossa coluna "descricao_local", apenas com esses dados que foram selecionados para NÃO remover.

Mas e se precisássemos remover os hífen `-` que não compões palavras ? Como poderiamos fazer isso ?

Utilizando um código semelhante, porém passando um novo parâmetro para fazermos a seleção:

In [ ]:
dados["descricao_local"] = dados["descricao_local"].str.replace("(?<!\w)-(?!\w)", " ", regex=True)

- `(?<!\w)`: uma "lookbehind" negativa que verifica se há um caractere de palavra antes do hífen ou se há apenas um espaço em branco, resultando em "verdadeiro" se não houver nada

- `(?!\w)`: uma lookahead negativa que verifica se há um caractere de palavra depois do hífen.

Com isso, podemos garantir que se não houver nenhuma palavra antes e nem depois vamos estar substituindo por espaço em branco

In [ ]:
dados["descricao_local"]

0       this clean and comfortable one bedroom sits ri...
1       our century old upper queen anne house is loca...
2       cozy room in two-bedroom apartment along the l...
3       very lovely and cozy room for one  convenientl...
4       the  studio at mibbett hollow' is in a beautif...
                              ...
3813    beautiful craftsman home in the historic wedgw...
3814    located in a very easily accessible area of se...
3815    this home is fully furnished and available wee...
3816    this business-themed modern home features    h...
3817    this welcoming home is in the quiet residentia...
Name: descricao_local, Length: 3818, dtype: object

# Tokenização de Strings

Para realizarmos a tokenização de strings, podemos simplesmente utilizar a função `split()`. Ela faz com que seja separado cada palavra após um espaço, deixando nossa coluna `descricao_local` da seguinte forma:

In [ ]:
dados["descricao_local"] = dados["descricao_local"].str.split()
dados["descricao_local"]

0       [this, clean, and, comfortable, one, bedroom, ...
1       [our, century, old, upper, queen, anne, house,...
2       [cozy, room, in, two-bedroom, apartment, along...
3       [very, lovely, and, cozy, room, for, one, conv...
4       [the, studio, at, mibbett, hollow', is, in, a,...
                              ...
3813    [beautiful, craftsman, home, in, the, historic...
3814    [located, in, a, very, easily, accessible, are...
3815    [this, home, is, fully, furnished, and, availa...
3816    [this, business-themed, modern, home, features...
3817    [this, welcoming, home, is, in, the, quiet, re...
Name: descricao_local, Length: 3818, dtype: object

In [ ]:
# Agora vamos fazer a mesma coisa com a coluna "comodidades"
dados["comodidades"]

0       {Internet,"Wireless Internet",Kitchen,"Free Pa...
1       {TV,Internet,"Wireless Internet",Kitchen,"Free...
2       {TV,Internet,"Wireless Internet",Kitchen,"Free...
3       {Internet,"Wireless Internet",Kitchen,"Free Pa...
4       {"Wireless Internet",Kitchen,"Free Parking on ...
                              ...
3813    {TV,"Cable TV",Internet,"Wireless Internet","A...
3814    {TV,"Cable TV",Internet,"Wireless Internet",Ki...
3815    {TV,"Cable TV",Internet,"Wireless Internet","A...
3816    {TV,"Cable TV",Internet,"Wireless Internet","A...
3817    {TV,Internet,"Wireless Internet",Kitchen,"Free...
Name: comodidades, Length: 3818, dtype: object

In [ ]:
# Usando seguinte código para remover a abertura e o fechamento das chaves e as aspas duplas

dados["comodidades"] = dados["comodidades"].str.replace('|{|}|\"', "", regex=True)
dados["comodidades"]

0       Internet,Wireless Internet,Kitchen,Free Parkin...
1       TV,Internet,Wireless Internet,Kitchen,Free Par...
2       TV,Internet,Wireless Internet,Kitchen,Free Par...
3       Internet,Wireless Internet,Kitchen,Free Parkin...
4       Wireless Internet,Kitchen,Free Parking on Prem...
                              ...
3813    TV,Cable TV,Internet,Wireless Internet,Air Con...
3814    TV,Cable TV,Internet,Wireless Internet,Kitchen...
3815    TV,Cable TV,Internet,Wireless Internet,Air Con...
3816    TV,Cable TV,Internet,Wireless Internet,Air Con...
3817    TV,Internet,Wireless Internet,Kitchen,Free Par...
Name: comodidades, Length: 3818, dtype: object

In [ ]:
# Passando como parâmentro na função split para especificar que o separador é a virgula
dados["comodidades"] = dados["comodidades"].str.split(",")

In [ ]:
dados.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,"[this, clean, and, comfortable, one, bedroom, ...",Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"[Internet, Wireless Internet, Kitchen, Free Pa...",0.0,0.0,110.0
1,10.0,--,1,"[our, century, old, upper, queen, anne, house,...","Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"[TV, Internet, Wireless Internet, Kitchen, Fre...",0.0,0.0,45.0
2,10.0,--,1,"[cozy, room, in, two-bedroom, apartment, along...",The convenience of being in Seattle but on the...,1,1,1,Futon,"[TV, Internet, Wireless Internet, Kitchen, Fre...",0.0,0.0,55.0
3,10.0,--,1,"[very, lovely, and, cozy, room, for, one, conv...","Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"[Internet, Wireless Internet, Kitchen, Free Pa...",0.0,20.0,52.0
4,10.0,--,1,"[the, studio, at, mibbett, hollow', is, in, a,...",--,1,1,1,Real Bed,"[Wireless Internet, Kitchen, Free Parking on P...",0.0,15.0,85.0

# Exercício Extra

Aplique a tokenização para a coluna `descricao_vizinhaca`

In [ ]:
dados["descricao_vizinhanca"]

0       Lower Queen Anne is near the Seattle Center (s...
1       Upper Queen Anne is a really pleasant, unique ...
2       The convenience of being in Seattle but on the...
3       Ballard is lovely, vibrant and one of the most...
4                                                      --
                              ...
3813                                                   --
3814    Quiet, dead end street near I-5. The proximity...
3815                                                   --
3816    Your hosts made Madison Valley their home when...
3817    Despite the quiet, leafy streets of this resid...
Name: descricao_vizinhanca, Length: 3818, dtype: object

In [ ]:
# Transformando em letras minúsculas
dados["descricao_vizinhanca"] = dados["descricao_vizinhanca"].str.lower()

In [ ]:
# Aplicando regex para execeção do que remover
dados["descricao_vizinhanca"] = dados["descricao_vizinhanca"].str.replace("^a-zA-Z0-9\-\'", " ", regex = True)

In [ ]:
# Aplicando regex, para remoção de hífens que não possuem palavras antes e depois
dados["descricao_vizinhanca"] = dados["descricao_vizinhanca"].str.replace("(?<!\w)-(?!\w)", "", regex = True)

In [ ]:
# Aplicando a separação de cada palavra por virgula e guarndando em uma lista
dados["descricao_vizinhanca"] = dados["descricao_vizinhanca"].str.split()

In [ ]:
dados["descricao_vizinhanca"]

0       [lower, queen, anne, is, near, the, seattle, c...
1       [upper, queen, anne, is, a, really, pleasant,,...
2       [the, convenience, of, being, in, seattle, but...
3       [ballard, is, lovely,, vibrant, and, one, of, ...
4                                                      []
                              ...
3813                                                   []
3814    [quiet,, dead, end, street, near, i-5., the, p...
3815                                                   []
3816    [your, hosts, made, madison, valley, their, ho...
3817    [despite, the, quiet,, leafy, streets, of, thi...
Name: descricao_vizinhanca, Length: 3818, dtype: object

# Manipulação com Dados em Tempo

Para as próximas análises, trabalharemos com a biblioteca `datetime` para manipularmos e tratarmos desde: data, hora, minuto, segundos, microssegundos, dias da semana, anos e etc.

Para utilizar-mos, precisamos apenas imnporta-lá em nossa linha de código, pois é uma das bibliotecas já inclusas no python.

Com isso, vamos fazer alguns testes até de fato, trabalharmos com bate de dados onde manipularemos dados relacionaodos ao tempo.

In [ ]:
# Data e Hora atual

import datetime

# Com essa função pegamos a data e a hora no momento que executarmos o código
atual = datetime.datetime.now()

# Exibição
print(f"Data e hora atual: {atual}")

Data e hora atual: 2023-09-24 01:40:34.181206

In [ ]:
# Data atual

# Função para pegar o dia atual
data = datetime.date.today()

# Exibição
print(f'Data atual é: {data}')

Data atual é: 2023-09-24

# Transformando os dados para tempo

O objetivo desse módulo é trabalhar com uma coluna onde o tipo dela não possui o datetime, e vamos fazer a conversão dela utilizando funções que o Pandas nos permite.

In [ ]:
# Importando novo DateFrame

dados_imoveis = pd.read_json("/content/moveis_disponiveis.json")
dados_imoveis.head()

    id        data  vaga_disponivel preco
0  857  2016-01-04            False  None
1  857  2016-01-05            False  None
2  857  2016-01-06            False  None
3  857  2016-01-07            False  None
4  857  2016-01-08            False  None

In [ ]:
# Verificando os tipos de cada coluna

dados_imoveis.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               365000 non-null  int64
 1   data             365000 non-null  object
 2   vaga_disponivel  365000 non-null  bool
 3   preco            270547 non-null  object
dtypes: bool(1), int64(1), object(2)
memory usage: 11.5+ MB

In [ ]:
# Convertendo a coluna "data" para o tipo "datetime"

dados_imoveis["data"] = pd.to_datetime(dados_imoveis["data"])

In [ ]:
dados_imoveis.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               365000 non-null  int64
 1   data             365000 non-null  datetime64[ns]
 2   vaga_disponivel  365000 non-null  bool
 3   preco            270547 non-null  object
dtypes: bool(1), datetime64[ns](1), int64(1), object(1)
memory usage: 11.5+ MB

Com isso fizemos a verificação do tipo de cada coluna, e fizemos a conversão da coluna "data" para o tipo correto, que pertence ao tipo `datetime`.

# Manipulação de dados Temporais

Vamos fazer o agrupamento da coluna `data`, para vermos quantas vagas disponivel há em cada mês. Por exemplo, sabemos que nosso dataframe possui 4 colunas, e trabalharemos com a coluna `data` e `vaga_disponivel`, com elas vamos fazer um agrupamento para saber quanto imoveis estão disponível por cada mês:

Ex.:
- Janeiro = 100
- Fevereiro = 1234
- ...

In [ ]:
dados_imoveis["data"]

0        2016-01-04
1        2016-01-05
2        2016-01-06
3        2016-01-07
4        2016-01-08
            ...
364995   2016-12-29
364996   2016-12-30
364997   2016-12-31
364998   2017-01-01
364999   2017-01-02
Name: data, Length: 365000, dtype: datetime64[ns]

In [ ]:
# Vamos utilizar o método strftime para converter os valores de datas para o formato que quisermos
# adicionamos o "dt" para chamar o tipo datetime

dados_imoveis["data"].dt.strftime("%Y-%m")

0         2016-01
1         2016-01
2         2016-01
3         2016-01
4         2016-01
           ...
364995    2016-12
364996    2016-12
364997    2016-12
364998    2017-01
364999    2017-01
Name: data, Length: 365000, dtype: object

In [ ]:
# Com isso agora, vamos fazer o agrupamento por cada mês
# Vamos adicionar ao final a função "sum()" para fazermos a soma da coluna vaga_disponivel, onde False=0 e True=1
meses_agrupados = dados_imoveis.groupby(dados_imoveis["data"].dt.strftime("%Y-%m"))["vaga_disponivel"].sum()

In [ ]:
meses_agrupados

data
2016-01    16543
2016-02    20128
2016-03    23357
2016-04    22597
2016-05    23842
2016-06    23651
2016-07    22329
2016-08    22529
2016-09    22471
2016-10    23765
2016-11    23352
2016-12    24409
2017-01     1574
Name: vaga_disponivel, dtype: int64

# Exercício Extra

Faça a transformação dos dados na coluna preco do conjunto de dados moveis_disponiveis.json para o tipo numérico float64. Lembrando que, antes de fazer isso, você precisa preencher os valores vazios na coluna por um valor. Uma sugestão: substitua pela string '0.0'

In [ ]:
dados_imoveis

          id        data  vaga_disponivel    preco
0        857  2016-01-04            False     None
1        857  2016-01-05            False     None
2        857  2016-01-06            False     None
3        857  2016-01-07            False     None
4        857  2016-01-08            False     None
...      ...         ...              ...      ...
364995  3279  2016-12-29             True  $140.00
364996  3279  2016-12-30             True  $140.00
364997  3279  2016-12-31             True  $140.00
364998  3279  2017-01-01             True  $140.00
364999  3279  2017-01-02            False     None

[365000 rows x 4 columns]

In [ ]:
# Tratando os dados da coluna "preco" antes de converte-lá

dados_imoveis["preco"] = dados_imoveis["preco"].str.replace("[^0-9]", "", regex= True)

In [ ]:
# Convertendo valores NaN por "0.0" usando método "fillna" que podemos passar como parâmetro para o que queremos converte-lo

dados_imoveis["preco"] = dados_imoveis["preco"].fillna("0.0")

In [ ]:
# Convertendo coluna "preco"

dados_imoveis["preco"] = dados_imoveis["preco"].astype(np.float64)

In [ ]:
dados_imoveis["preco"]

0             0.0
1             0.0
2             0.0
3             0.0
4             0.0
           ...
364995    14000.0
364996    14000.0
364997    14000.0
364998    14000.0
364999        0.0
Name: preco, Length: 365000, dtype: float64

In [ ]:
# Verificando o tipo de dados de cada coluna
dados_imoveis.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               365000 non-null  int64
 1   data             365000 non-null  object
 2   vaga_disponivel  365000 non-null  bool
 3   preco            365000 non-null  float64
dtypes: bool(1), float64(1), int64(1), object(1)
memory usage: 11.5+ MB

# Conclusão

- Tratamos os dados em listas
- Transformamos dados numéricos, inclusive os que estavam entre caracteres textuais
- Manipulamos dados de texto com regex
- Conhecemos o tipo datetime para dados de tempo
- Transformamos o tipo da nossa base em datetime
- Manipulamos e criamos outra base a partir dos dados de tempo